services:
  postgres:
    image: postgres:16
    container_name: grid07_postgres
    environment:
      POSTGRES_DB: grid07db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: grid07_redis
    ports:
      - "6379:6379"